import {
  Component,
  Injector,
  OnInit,
  EventEmitter,
  Output,
} from '@angular/core';
import{CountriesList} from './CountriesList';
import{CapitalsList} from './CapitalsList';
import { BsModalRef } from 'ngx-bootstrap/modal';
import { AppComponentBase } from '@shared/app-component-base';
import {
CountryServiceProxy,
CountryDto,
    CreateCountryDto,
    CountryEditDto
} from '@shared/service-proxies/service-proxies';
import { forEach as _forEach, map as _map } from 'lodash-es';


@Component({
  templateUrl: 'edit-country-dialog.component.html'
})
export class EditCounteriesComponent extends AppComponentBase
  implements OnInit {
  saving = false;
    country = new CountryEditDto();
  countries:CountriesList[];
  Capitals:CapitalsList[];
  @Output() onSave = new EventEmitter<any>();

  constructor(
    injector: Injector,
    private _CountryService: CountryServiceProxy,
    public bsModalRef: BsModalRef
  ) {
    super(injector);
  }

  ngOnInit(): void {
   // this._CountryService
   this.countries=[
    { id:"Afghanistan",Name:"Afghanistan"},
{ id:"Albania",Name:"Albania"},
{ id:"Algeria",Name:"Algeria"},
{ id:"Andorra",Name:"Andorra"},
{ id:"Angola",Name:"Angola"},
{ id:"Antigua and Barbuda",Name:"Antigua and Barbuda"},
{ id:"Argentina",Name:"Argentina"},
{ id:"Armenia",Name:"Armenia"},
{ id:"Australia",Name:"Australia"},
{ id:"Austria",Name:"Austria"},
{ id:"Azerbaijan",Name:"Azerbaijan"},
{ id:"Bahamas",Name:"Bahamas"},
{ id:"Bahrain",Name:"Bahrain"},
{ id:"Bangladesh",Name:"Bangladesh"},
{ id:"Barbados",Name:"Barbados"},
{ id:"Belarus",Name:"Belarus"},
{ id:"Belgium",Name:"Belgium"},
{ id:"Belize",Name:"Belize"},
{ id:"Benin",Name:"Benin"},
{ id:"Bhutan",Name:"Bhutan"},
{ id:"Bolivia",Name:"Bolivia"},
{ id:"Bosnia and Herzegovina",Name:"Bosnia and Herzegovina"},
{ id:"Botswana",Name:"Botswana"},
{ id:"Brazil",Name:"Brazil"},
{ id:"Brunei",Name:"Brunei"},
{ id:"Bulgaria",Name:"Bulgaria"},
{ id:"Burkina Faso",Name:"Burkina Faso"},
{ id:"Burundi",Name:"Burundi"},
{ id:"Cambodia",Name:"Cambodia"},
{ id:"Cameroon",Name:"Cameroon"},
{ id:"Canada",Name:"Canada"},
{ id:"Cape Verde",Name:"Cape Verde"},
{ id:"Central African Republic",Name:"Central African Republic"},
{ id:"Chad",Name:"Chad"},
{ id:"Chile",Name:"Chile"},
{ id:"China",Name:"China"},
{ id:"Colombia",Name:"Colombia"},
{ id:"Comoros",Name:"Comoros"},
{ id:"Congo, Democratic Republic of the",Name:"Congo, Democratic Republic of the"},
{ id:"Congo, Republic of the",Name:"Congo, Republic of the"},
{ id:"Costa Rica",Name:"Costa Rica"},
{ id:"Côte d'Ivoire (Ivory Coast)",Name:"Côte d'Ivoire (Ivory Coast)"},
{ id:"Croatia",Name:"Croatia"},
{ id:"Cuba",Name:"Cuba"},
{ id:"Cyprus",Name:"Cyprus"},
{ id:"Czech Republic (Czechia)[5]",Name:"Czech Republic (Czechia)[5]"},
{ id:"Denmark",Name:"Denmark"},
{ id:"Djibouti",Name:"Djibouti"},
{ id:"Dominica",Name:"Dominica"},
{ id:"Dominican Republic",Name:"Dominican Republic"},
{ id:"East Timor",Name:"East Timor"},
{ id:"Ecuador",Name:"Ecuador"},
{ id:"Egypt",Name:"Egypt"},
{ id:"El Salvador",Name:"El Salvador"},
{ id:"England[6]",Name:"England[6]"},
{ id:"Equatorial Guinea",Name:"Equatorial Guinea"},
{ id:"Eritrea",Name:"Eritrea"},
{ id:"Estonia",Name:"Estonia"},
{ id:"Eswatini (Swaziland)[7]",Name:"Eswatini (Swaziland)[7]"},
{ id:"Ethiopia",Name:"Ethiopia"},
{ id:"Federated States of Micronesia",Name:"Federated States of Micronesia"},
{ id:"Fiji",Name:"Fiji"},
{ id:"Finland",Name:"Finland"},
{ id:"France",Name:"France"},
{ id:"Gabon",Name:"Gabon"},
{ id:"Gambia",Name:"Gambia"},
{ id:"Georgia",Name:"Georgia"},
{ id:"Germany",Name:"Germany"},
{ id:"Ghana",Name:"Ghana"},
{ id:"Greece",Name:"Greece"},
{ id:"Grenada",Name:"Grenada"},
{ id:"Guatemala",Name:"Guatemala"},
{ id:"Guinea",Name:"Guinea"},
{ id:"Guinea-Bissau",Name:"Guinea-Bissau"},
{ id:"Guyana",Name:"Guyana"},
{ id:"Haiti",Name:"Haiti"},
{ id:"Honduras",Name:"Honduras"},
{ id:"Hungary",Name:"Hungary"},
{ id:"Iceland",Name:"Iceland"},
{ id:"India",Name:"India"},
{ id:"Indonesia",Name:"Indonesia"},
{ id:"Iran",Name:"Iran"},
{ id:"Iraq",Name:"Iraq"},
{ id:"Ireland",Name:"Ireland"},
{ id:"Israel",Name:"Israel"},
{ id:"Italy",Name:"Italy"},
{ id:"Jamaica",Name:"Jamaica"},
{ id:"Japan",Name:"Japan"},
{ id:"Jordan",Name:"Jordan"},
{ id:"Kazakhstan",Name:"Kazakhstan"},
{ id:"Kenya",Name:"Kenya"},
{ id:"Kiribati",Name:"Kiribati"},
{ id:"Kosovo",Name:"Kosovo"},
{ id:"Kuwait",Name:"Kuwait"},
{ id:"Kyrgyzstan",Name:"Kyrgyzstan"},
{ id:"Laos",Name:"Laos"},
{ id:"Latvia",Name:"Latvia"},
{ id:"Lebanon",Name:"Lebanon"},
{ id:"Lesotho",Name:"Lesotho"},
{ id:"Liberia",Name:"Liberia"},
{ id:"Libya",Name:"Libya"},
{ id:"Liechtenstein",Name:"Liechtenstein"},
{ id:"Lithuania",Name:"Lithuania"},
{ id:"Luxembourg",Name:"Luxembourg"},
{ id:"Madagascar",Name:"Madagascar"},
{ id:"Malawi",Name:"Malawi"},
{ id:"Malaysia",Name:"Malaysia"},
{ id:"Maldives",Name:"Maldives"},
{ id:"Mali",Name:"Mali"},
{ id:"Malta",Name:"Malta"},
{ id:"Marshall Islands",Name:"Marshall Islands"},
{ id:"Mauritania",Name:"Mauritania"},
{ id:"Mauritius",Name:"Mauritius"},
{ id:"Mexico",Name:"Mexico"},
{ id:"Moldova",Name:"Moldova"},
{ id:"Monaco",Name:"Monaco"},
{ id:"Mongolia",Name:"Mongolia"},
{ id:"Montenegro",Name:"Montenegro"},
{ id:"Morocco",Name:"Morocco"},
{ id:"Mozambique",Name:"Mozambique"},
{ id:"Myanmar (Burma)",Name:"Myanmar (Burma)"},
{ id:"Namibia",Name:"Namibia"},
{ id:"Nauru",Name:"Nauru"},
{ id:"Nepal",Name:"Nepal"},
{ id:"Netherlands",Name:"Netherlands"},
{ id:"New Zealand",Name:"New Zealand"},
{ id:"Nicaragua",Name:"Nicaragua"},
{ id:"Niger",Name:"Niger"},
{ id:"Nigeria",Name:"Nigeria"},
{ id:"North Korea",Name:"North Korea"},
{ id:"North Macedonia (Macedonia)[14]",Name:"North Macedonia (Macedonia)[14]"},
{ id:"Northern Ireland[15]",Name:"Northern Ireland[15]"},
{ id:"Norway",Name:"Norway"},
{ id:"Oman",Name:"Oman"},
{ id:"Pakistan",Name:"Pakistan"},
{ id:"Palau",Name:"Palau"},
{ id:"Panama",Name:"Panama"},
{ id:"Papua New Guinea",Name:"Papua New Guinea"},
{ id:"Paraguay",Name:"Paraguay"},
{ id:"Peru",Name:"Peru"},
{ id:"Philippines",Name:"Philippines"},
{ id:"Poland",Name:"Poland"},
{ id:"Portugal",Name:"Portugal"},
{ id:"Qatar",Name:"Qatar"},
{ id:"Romania",Name:"Romania"},
{ id:"Russia",Name:"Russia"},
{ id:"Rwanda",Name:"Rwanda"},
{ id:"Saint Kitts and Nevis",Name:"Saint Kitts and Nevis"},
{ id:"Saint Lucia",Name:"Saint Lucia"},
{ id:"Saint Vincent and the Grenadines",Name:"Saint Vincent and the Grenadines"},
{ id:"Samoa",Name:"Samoa"},
{ id:"San Marino",Name:"San Marino"},
{ id:"Sao Tome and Principe",Name:"Sao Tome and Principe"},
{ id:"Saudi Arabia",Name:"Saudi Arabia"},
{ id:"Scotland[16]",Name:"Scotland[16]"},
{ id:"Senegal",Name:"Senegal"},
{ id:"Serbia",Name:"Serbia"},
{ id:"Seychelles",Name:"Seychelles"},
{ id:"Sierra Leone",Name:"Sierra Leone"},
{ id:"Singapore",Name:"Singapore"},
{ id:"Slovakia",Name:"Slovakia"},
{ id:"Slovenia",Name:"Slovenia"},
{ id:"Solomon Islands",Name:"Solomon Islands"},
{ id:"Somalia",Name:"Somalia"},
{ id:"South Africa",Name:"South Africa"},
{ id:"South Korea",Name:"South Korea"},
{ id:"South Sudan",Name:"South Sudan"},
{ id:"Spain",Name:"Spain"},
{ id:"Sri Lanka",Name:"Sri Lanka"},
{ id:"Sudan",Name:"Sudan"},
{ id:"Suriname",Name:"Suriname"},
{ id:"Sweden",Name:"Sweden"},
{ id:"Switzerland",Name:"Switzerland"},
{ id:"Syria",Name:"Syria"},
{ id:"Taiwan[19]",Name:"Taiwan[19]"},
{ id:"Tajikistan",Name:"Tajikistan"},
{ id:"Tanzania",Name:"Tanzania"},
{ id:"Thailand",Name:"Thailand"},
{ id:"Togo",Name:"Togo"},
{ id:"Tonga",Name:"Tonga"},
{ id:"Trinidad and Tobago",Name:"Trinidad and Tobago"},
{ id:"Tunisia",Name:"Tunisia"},
{ id:"Türkiye (Turkey)[21]",Name:"Türkiye (Turkey)[21]"},
{ id:"Turkmenistan",Name:"Turkmenistan"},
{ id:"Tuvalu",Name:"Tuvalu"},
{ id:"Uganda",Name:"Uganda"},
{ id:"Ukraine",Name:"Ukraine"},
{ id:"United Arab Emirates",Name:"United Arab Emirates"},
{ id:"United Kingdom",Name:"United Kingdom"},
{ id:"United States",Name:"United States"},
{ id:"Uruguay",Name:"Uruguay"},
{ id:"Uzbekistan",Name:"Uzbekistan"},
{ id:"Vanuatu",Name:"Vanuatu"},
{ id:"Vatican City",Name:"Vatican City"},
{ id:"Venezuela",Name:"Venezuela"},
{ id:"Vietnam",Name:"Vietnam"},
{ id:"Wales[23]",Name:"Wales[23]"},
{ id:"Yemen",Name:"Yemen"},
{ id:"Zambia",Name:"Zambia"},
{ id:"Zimbabwe",Name:"Zimbabwe"}

   ];

this.Capitals=[
    { id: "Afghanistan", Name: "Kabul" },
    { id: "Albania", Name: "Tirana (Tirane)" },
    { id: "Algeria", Name: "Algiers" },
    { id: "Andorra", Name: "Andorra la Vella" },
    { id: "Angola", Name: "Luanda" },
    { id: "Antigua and Barbuda", Name: "Saint John's" },
    { id: "Argentina", Name: "Buenos Aires" },
    { id: "Armenia", Name: "Yerevan" },
    { id: "Australia", Name: "Canberra" },
    { id: "Austria", Name: "Vienna" },
    { id: "Azerbaijan", Name: "Baku" },
    { id: "Bahamas", Name: "Nassau" },
    { id: "Bahrain", Name: "Manama" },
    { id: "Bangladesh", Name: "Dhaka" },
    { id: "Barbados", Name: "Bridgetown" },
    { id: "Belarus", Name: "Minsk" },
    { id: "Belgium", Name: "Brussels" },
    { id: "Belize", Name: "Belmopan" },
    { id: "Benin", Name: "Porto Novo[1]" },
    { id: "Bhutan", Name: "Thimphu" },
    { id: "Bolivia", Name: "La Paz (administrative), Sucre (official)[2]" },
    { id: "Bosnia and Herzegovina", Name: "Sarajevo" },
    { id: "Botswana", Name: "Gaborone" },
    { id: "Brazil", Name: "Brasilia" },
    { id: "Brunei", Name: "Bandar Seri Begawan" },
    { id: "Bulgaria", Name: "Sofia" },
    { id: "Burkina Faso", Name: "Ouagadougou" },
    { id: "Burundi", Name: "Gitega[3]" },
    { id: "Cambodia", Name: "Phnom Penh" },
    { id: "Cameroon", Name: "Yaounde" },
    { id: "Canada", Name: "Ottawa" },
    { id: "Cape Verde", Name: "Praia" },
    { id: "Central African Republic", Name: "Bangui" },
    { id: "Chad", Name: "N'Djamena" },
    { id: "Chile", Name: "Santiago" },
    { id: "China", Name: "Beijing" },
    { id: "Colombia", Name: "Bogota" },
    { id: "Comoros", Name: "Moroni" },
    { id: "Congo, Democratic Republic of the", Name: "Kinshasa" },
    { id: "Congo, Republic of the", Name: "Brazzaville" },
    { id: "Costa Rica", Name: "San Jose" },
    { id: "Côte d'Ivoire (Ivory Coast)", Name: "Yamoussoukro[4]" },
    { id: "Croatia", Name: "Zagreb" },
    { id: "Cuba", Name: "Havana" },
    { id: "Cyprus", Name: "Nicosia" },
    { id: "Czech Republic (Czechia)[5]", Name: "Prague" },
    { id: "Denmark", Name: "Copenhagen" },
    { id: "Djibouti", Name: "Djibouti" },
    { id: "Dominica", Name: "Roseau" },
    { id: "Dominican Republic", Name: "Santo Domingo" },
    { id: "East Timor", Name: "Dili" },
    { id: "Ecuador", Name: "Quito" },
    { id: "Egypt", Name: "Cairo" },
    { id: "El Salvador", Name: "San Salvador" },
    { id: "England[6]", Name: "London" },
    { id: "Equatorial Guinea", Name: "Malabo" },
    { id: "Eritrea", Name: "Asmara" },
    { id: "Estonia", Name: "Tallinn" },
    { id: "Eswatini (Swaziland)[7]", Name: "Mbabana[8]" },
    { id: "Ethiopia", Name: "Addis Ababa" },
    { id: "Federated States of Micronesia", Name: "Palikir" },
    { id: "Fiji", Name: "Suva" },
    { id: "Finland", Name: "Helsinki" },
    { id: "France", Name: "Paris" },
    { id: "Gabon", Name: "Libreville" },
    { id: "Gambia", Name: "Banjul" },
    { id: "Georgia", Name: "Tbilisi" },
    { id: "Germany", Name: "Berlin" },
    { id: "Ghana", Name: "Accra" },
    { id: "Greece", Name: "Athens" },
    { id: "Grenada", Name: "Saint George's" },
    { id: "Guatemala", Name: "Guatemala City" },
    { id: "Guinea", Name: "Conakry" },
    { id: "Guinea-Bissau", Name: "Bissau" },
    { id: "Guyana", Name: "Georgetown" },
    { id: "Haiti", Name: "Port au Prince" },
    { id: "Honduras", Name: "Tegucigalpa" },
    { id: "Hungary", Name: "Budapest" },
    { id: "Iceland", Name: "Reykjavik" },
    { id: "India", Name: "New Delhi" },
    { id: "Indonesia", Name: "Jakarta" },
    { id: "Iran", Name: "Tehran" },
    { id: "Iraq", Name: "Baghdad" },
    { id: "Ireland", Name: "Dublin" },
    { id: "Israel", Name: "Jerusalem (very limited international recognition)[9]" },
    { id: "Italy", Name: "Rome" },
    { id: "Jamaica", Name: "Kingston" },
    { id: "Japan", Name: "Tokyo" },
    { id: "Jordan", Name: "Amman" },
    { id: "Kazakhstan", Name: "Nur-Sultan[10]" },
    { id: "Kenya", Name: "Nairobi" },
    { id: "Kiribati", Name: "Tarawa Atoll" },
    { id: "Kosovo", Name: "Pristina" },
    { id: "Kuwait", Name: "Kuwait City" },
    { id: "Kyrgyzstan", Name: "Bishkek" },
    { id: "Laos", Name: "Vientiane" },
    { id: "Latvia", Name: "Riga" },
    { id: "Lebanon", Name: "Beirut" },
    { id: "Lesotho", Name: "Maseru" },
    { id: "Liberia", Name: "Monrovia" },
    { id: "Libya", Name: "Tripoli" },
    { id: "Liechtenstein", Name: "Vaduz" },
    { id: "Lithuania", Name: "Vilnius" },
    { id: "Luxembourg", Name: "Luxembourg" },
    { id: "Madagascar", Name: "Antananarivo" },
    { id: "Malawi", Name: "Lilongwe" },
    { id: "Malaysia", Name: "Kuala Lumpur[11]" },
    { id: "Maldives", Name: "Male" },
    { id: "Mali", Name: "Bamako" },
    { id: "Malta", Name: "Valletta" },
    { id: "Marshall Islands", Name: "Majuro" },
    { id: "Mauritania", Name: "Nouakchott" },
    { id: "Mauritius", Name: "Port Louis" },
    { id: "Mexico", Name: "Mexico City" },
    { id: "Moldova", Name: "Chisinau" },
    { id: "Monaco", Name: "Monaco" },
    { id: "Mongolia", Name: "Ulaanbaatar" },
    { id: "Montenegro", Name: "Podgorica" },
    { id: "Morocco", Name: "Rabat" },
    { id: "Mozambique", Name: "Maputo" },
    { id: "Myanmar (Burma)", Name: "Nay Pyi Taw[12]" },
    { id: "Namibia", Name: "Windhoek" },
    { id: "Nauru", Name: "No official capital" },
    { id: "Nepal", Name: "Kathmandu" },
    { id: "Netherlands", Name: "Amsterdam[13]" },
    { id: "New Zealand", Name: "Wellington" },
    { id: "Nicaragua", Name: "Managua" },
    { id: "Niger", Name: "Niamey" },
    { id: "Nigeria", Name: "Abuja" },
    { id: "North Korea", Name: "Pyongyang" },
    { id: "North Macedonia (Macedonia)[14]", Name: "Skopje" },
    { id: "Northern Ireland[15]", Name: "Belfast" },
    { id: "Norway", Name: "Oslo" },
    { id: "Oman", Name: "Muscat" },
    { id: "Pakistan", Name: "Islamabad" },
    { id: "Palau", Name: "Melekeok" },
    { id: "Panama", Name: "Panama City" },
    { id: "Papua New Guinea", Name: "Port Moresby" },
    { id: "Paraguay", Name: "Asuncion" },
    { id: "Peru", Name: "Lima" },
    { id: "Philippines", Name: "Manila" },
    { id: "Poland", Name: "Warsaw" },
    { id: "Portugal", Name: "Lisbon" },
    { id: "Qatar", Name: "Doha" },
    { id: "Romania", Name: "Bucharest" },
    { id: "Russia", Name: "Moscow" },
    { id: "Rwanda", Name: "Kigali" },
    { id: "Saint Kitts and Nevis", Name: "Basseterre" },
    { id: "Saint Lucia", Name: "Castries" },
    { id: "Saint Vincent and the Grenadines", Name: "Kingstown" },
    { id: "Samoa", Name: "Apia" },
    { id: "San Marino", Name: "San Marino" },
    { id: "Sao Tome and Principe", Name: "Sao Tome" },
    { id: "Saudi Arabia", Name: "Riyadh" },
    { id: "Scotland[16]", Name: "Edinburgh" },
    { id: "Senegal", Name: "Dakar" },
    { id: "Serbia", Name: "Belgrade" },
    { id: "Seychelles", Name: "Victoria" },
    { id: "Sierra Leone", Name: "Freetown" },
    { id: "Singapore", Name: "Singapore" },
    { id: "Slovakia", Name: "Bratislava" },
    { id: "Slovenia", Name: "Ljubljana" },
    { id: "Solomon Islands", Name: "Honiara" },
    { id: "Somalia", Name: "Mogadishu" },
    { id: "South Africa", Name: "Pretoria, Bloemfontein, Cape Town[17]" },
    { id: "South Korea", Name: "Seoul" },
    { id: "South Sudan", Name: "Juba" },
    { id: "Spain", Name: "Madrid" },
    { id: "Sri Lanka", Name: "Sri Jayawardenapura Kotte[18]" },
    { id: "Sudan", Name: "Khartoum" },
    { id: "Suriname", Name: "Paramaribo" },
    { id: "Sweden", Name: "Stockholm" },
    { id: "Switzerland", Name: "Bern" },
    { id: "Syria", Name: "Damascus" },
    { id: "Taiwan[19]", Name: "Taipei" },
    { id: "Tajikistan", Name: "Dushanbe" },
    { id: "Tanzania", Name: "Dodoma[20]" },
    { id: "Thailand", Name: "Bangkok" },
    { id: "Togo", Name: "Lome" },
    { id: "Tonga", Name: "Nuku'alofa" },
    { id: "Trinidad and Tobago", Name: "Port of Spain" },
    { id: "Tunisia", Name: "Tunis" },
    { id: "Türkiye (Turkey)[21]", Name: "Ankara" },
    { id: "Turkmenistan", Name: "Ashgabat" },
    { id: "Tuvalu", Name: "Funafuti[22]" },
    { id: "Uganda", Name: "Kampala" },
    { id: "Ukraine", Name: "Kyiv or Kiev" },
    { id: "United Arab Emirates", Name: "Abu Dhabi" },
    { id: "United Kingdom", Name: "London" },
    { id: "United States", Name: "Washington D.C." },
    { id: "Uruguay", Name: "Montevideo" },
    { id: "Uzbekistan", Name: "Tashkent" },
    { id: "Vanuatu", Name: "Port Vila" },
    { id: "Vatican City", Name: "Vatican City" },
    { id: "Venezuela", Name: "Caracas" },
    { id: "Vietnam", Name: "Hanoi" },
    { id: "Wales[23]", Name: "Cardiff" },
    { id: "Yemen", Name: "Sana'a[24]" },
    { id: "Zambia", Name: "Lusaka" },
    { id: "Zimbabwe", Name: "Harare" }
];

  }
  save(): void {
    this.saving = true;

      const coutry = new CountryDto();
    coutry.init(this.country);
    //role.grantedPermissions = this.getCheckedPermissions();


      this._CountryService.update(coutry).subscribe(
          () => {
              this.notify.info(this.l('SavedSuccessfully'));
              this.bsModalRef.hide();
              this.onSave.emit();
          },
          () => {
              this.saving = false;
          }
      );
  }
    OnCountrySelected(event:any){
    this.country.name=event.target.options[event.target.options.selectedIndex].text;
  }
    OnCaptitalSelected(event: any) {
        this.country.capital = event.target.options[event.target.options.selectedIndex].text;
    }
}
